export const PRODUCT_CATEGORIES = [
  {id: 1, name: 'Asian & Local Veg'},
  {id: 2, name: 'Broccoli & Cauliflower'},
  {id: 3, name: 'Cabbage'},
  {id: 4, name: 'Fruits - Apples'},
  {id: 5, name: 'Fruits - Berries'},
  {id: 6, name: 'Fruits - Citrus'},
  {id: 7, name: 'Fruits - Exotics'},
  {id: 8, name: 'Fruits - Tropical'},
  {id: 9, name: 'Herbs'},
  {id: 10, name: 'Lettuces'},
  {id: 11, name: 'Mushroom'},
  {id: 12, name: 'Potatoes'},
  {id: 13, name: 'Processed Items'},
  {id: 14, name: 'Pumpkins'},
];

export const PRODUCTS = [
  {
    id: 1,
    name: 'Angled Gourd',
    image: require('assets/images/dummy.png'),
    price: 4.0,
    unit: 'KG (S)',
    categoryId: 1,
  },
  {
    id: 2,
    name: 'Arrow Root',
    image: require('assets/images/dummy.png'),
    price: 5.0,
    unit: 'KG (S)',
    categoryId: 1,
  },
  {
    id: 3,
    name: 'Asparagus Green',
    image: require('assets/images/dummy.png'),
    price: 30.0,
    unit: 'KG',
    categoryId: 1,
  },
  {
    id: 4,
    name: 'Baby Corn',
    price: 7.0,
    image: require('assets/images/dummy.png'),
    unit: 'Kilos (S)',
    categoryId: 1,
  },
];
